#!/bin/sh
fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

# Install Xcode Command Line Tools.
xcode-select --install

fancy_echo "Installing Homebrew ..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

fancy_echo "Generating SSH key ..."
ssh-keygen -t rsa -b 4096 -C "bob@vanderclay.net"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

pbcopy < ~/.ssh/id_rsa.pub
fancy_echo "Copied SSH key to clipboard ..."
