#!/bin/bash
fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "1.2"

# Install Xcode Command Line Tools.
xcode-select --install

#
# Check if Homebrew is installed
#
which -s brew
if [[ $? != 0 ]] ; then
    # Install Homebrew
    fancy_echo "Installing Homebrew ..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    fancy_echo "Updating Homebrew ..."
    brew update
fi

echo -e "\n"
read -p "Generate new (and backup any current) SSH keys? (y):" createkey </dev/tty

if [[ "${createkey:=y}" == "y" ]]; then
  echo -e "Generating new SSH keys...\n"
  read -p "Enter your email address: " email </dev/tty
  mkdir -p ~/.ssh/key_backup && mv ~/.ssh/id_rsa* ~/.ssh/key_backup
  echo -e "\n\n\n" | ssh-keygen -t rsa -N "" -C ${email:=null@example.com}
fi

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

pbcopy < ~/.ssh/id_rsa.pub
fancy_echo "Copied SSH key to clipboard ..."
fancy_echo "Add it to: https://github.com/settings/keys"
