- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  roles:
#    - {role: osx, when: ansible_os_family == "Darwin"}
    - git
    - zsh
    - vim
    - neovim
    - fzf
#    - python
    - node
#    - hub
#    - autoenv
    - ag
    - rust
    - exa
    - tmux
    - dnsmasq
    # - hyper
    - youtube-dl
    - php
    - go
    - emacs
#    - asdf
    - {role: hammerspoon, when: ansible_os_family == "Darwin"}
