
- include: osx.yml
  when: ansible_os_family == "Darwin"

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Check if .tmux.conf exists
  stat: path="{{dotfiles_user_home}}/.tmux.conf"
  register: tmuxconf_stat
  failed_when: False

- name: Backup .tmux.conf
  command: mv ~/.tmux.conf ~/.tmux.conf.bak
  args:
    creates: "{{dotfiles_user_home}}/.tmux.conf.bak"
  when: tmuxconf_stat.stat.exists

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link

- name: Install tmux plugins
  command: ~/.tmux/plugins/tpm/bin/install_plugins

- name: Update tmux plugins
  command: ~/.tmux/plugins/tpm/bin/update_plugins all
